version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
template_file = "pipeline.yml"
stack_name = "cloudprem-pipeline-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1k5khq956e42f"
s3_prefix = "cloudprem-pipeline-dev"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "RepositoryPath=\"development\" RepositoryBranch=\"master\" OwnerName=\"ronaldo@nclouds.com\" Environment=\"dev\""
