version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
template_file = "repository.yml"
stack_name = "cloudprem-repository"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1k5khq956e42f"
s3_prefix = "cloudprem-repository"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "RepositoryName=\"cloudprem\" OwnerName=\"ronaldo@nclouds.com\" Environment=\"dev\""
